name: uwmlgeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - rasterio
  - scipy
  - scikit-learn
  - torchvision
  - xarray
  - tensorflow
  - keras
